# Generated by Django 3.2.5 on 2021-10-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('sounds', '0001_initial'),
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.sound'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
