# Generated by Django 3.2.8 on 2021-10-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0004_alter_instrument_code'),
        ('show', '0005_auto_20211016_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phrase',
            name='used_on_track',
        ),
        migrations.RemoveField(
            model_name='phrase',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhraseType',
        ),
        migrations.AddField(
            model_name='request',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.instrument'),
        ),
        migrations.AddField(
            model_name='request',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.sound'),
        ),
        migrations.DeleteModel(
            name='Phrase',
        ),
    ]
