# Generated by Django 3.2.8 on 2021-10-16 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0006_auto_20211016_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='show.requesttype'),
            preserve_default=False,
        ),
    ]
