# Generated by Django 3.2.6 on 2021-10-16 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_saymyname'),
        ('show', '0010_alter_request_used_on_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='played_by',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='played_by', to='login.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='login.user'),
        ),
    ]
