# Generated by Django 3.2.8 on 2021-10-16 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_saymyname'),
        ('show', '0011_auto_20211016_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='played_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='played_by', to='users.user'),
        ),
    ]
