# Generated by Django 3.2.8 on 2021-10-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0012_alter_request_played_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
