# Generated by Django 3.2.6 on 2021-11-11 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0013_alter_request_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestType',
            new_name='Command',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='request_type',
            new_name='command',
        ),
    ]
