# Generated by Django 3.2.8 on 2021-11-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0014_auto_20211111_0315'),
        ('show', '0015_alter_request_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to='sounds.sound'),
        ),
    ]
