# Generated by Django 3.2.8 on 2021-11-28 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20211110_0411'),
        ('sounds', '0014_auto_20211111_0315'),
        ('show', '0016_alter_request_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.sound'),
        ),
        migrations.AlterField(
            model_name='request',
            name='used_on_track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_requests', to='mainsite.song'),
        ),
    ]
