# Generated by Django 4.0 on 2021-12-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0014_auto_20211111_0315'),
        ('show', '0017_auto_20211128_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='sound',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='sounds.sound'),
        ),
    ]
