# Generated by Django 3.2.8 on 2021-10-24 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPronoun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.CharField(max_length=10)),
                ('objective', models.CharField(max_length=10)),
                ('possessive', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
