# Generated by Django 3.2.5 on 2021-10-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_saymyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
