# Generated by Django 3.2.6 on 2021-10-16 02:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_soundrating_rating'),
        ('login', '0003_user_saymyname'),
        ('mainsite', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='songrating',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='venue',
            new_name='tour',
        ),
        migrations.AddField(
            model_name='song',
            name='instruments',
            field=models.ManyToManyField(blank=True, null=True, related_name='instruments', to='sounds.Instrument'),
        ),
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='track_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songrating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='named_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='sounds',
            field=models.ManyToManyField(blank=True, null=True, related_name='songs', to='sounds.Sound'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='named_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='named_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.CreateModel(
            name='VenueArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.CharField(max_length=100)),
                ('year', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
