# Generated by Django 3.2.8 on 2021-10-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20211016_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(max_length=10),
        ),
    ]
