# Generated by Django 3.2.8 on 2021-10-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_alter_song_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sounds',
        ),
    ]
