# Generated by Django 3.2.8 on 2021-10-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20211016_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
