# Generated by Django 3.2.8 on 2021-10-29 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20211029_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueart',
            name='venue',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='mainsite.venue'),
            preserve_default=False,
        ),
    ]
