# Generated by Django 3.2.5 on 2021-11-10 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_email'),
        ('mainsite', '0008_venueart_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='commissioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs_commissioned', to='users.user'),
        ),
        migrations.AddField(
            model_name='song',
            name='vod_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='named_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs_named', to='users.user'),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VenueSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandcamp', models.TextField(blank=True, null=True)),
                ('bandcamp_bitly', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.venue')),
            ],
        ),
        migrations.CreateModel(
            name='SongSocials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.song')),
            ],
        ),
    ]
