# Generated by Django 3.2.8 on 2021-12-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20211110_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url_slug',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='url_slug',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='url_slug',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
