# Generated by Django 4.0 on 2021-12-19 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_alter_song_url_slug_alter_tour_url_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsocials',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='mainsite.song'),
        ),
    ]
