# Generated by Django 3.2.6 on 2021-10-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_alter_sound_renamed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundrating',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
