# Generated by Django 3.2.8 on 2021-10-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0003_soundrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
