# Generated by Django 3.2.6 on 2021-10-16 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_saymyname'),
        ('sounds', '0004_alter_instrument_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='played_by',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
            preserve_default=False,
        ),
    ]
