# Generated by Django 3.2.6 on 2021-10-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_saymyname'),
        ('sounds', '0005_instrument_played_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to='users.user'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='played_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_by', to='users.user'),
        ),
    ]
