# Generated by Django 3.2.8 on 2021-10-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0007_auto_20211016_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundrating',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
