# Generated by Django 3.2.8 on 2021-10-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpronoun'),
        ('sounds', '0008_alter_soundrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundrating',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='sounds.sound'),
        ),
        migrations.AlterField(
            model_name='soundrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.user'),
        ),
    ]
