# Generated by Django 3.2.8 on 2021-10-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userpronoun'),
        ('sounds', '0009_auto_20211024_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundrating',
            name='sound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='sounds.sound'),
        ),
        migrations.AlterField(
            model_name='soundrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='login.user'),
        ),
    ]
