# Generated by Django 3.2.5 on 2021-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0010_auto_20211024_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
