# Generated by Django 3.2.5 on 2021-11-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0011_auto_20211111_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
