# Generated by Django 3.2.5 on 2021-11-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0013_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.category'),
        ),
        migrations.AlterField(
            model_name='sound',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sounds.subcategory'),
        ),
    ]
